[2024-08-20T10:23:36.797+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_4.scrape_post_links manual__2024-08-20T10:21:43.417140+00:00 [queued]>
[2024-08-20T10:23:36.803+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_4.scrape_post_links manual__2024-08-20T10:21:43.417140+00:00 [queued]>
[2024-08-20T10:23:36.803+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-08-20T10:23:36.814+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_post_links> on 2024-08-20 10:21:43.417140+00:00
[2024-08-20T10:23:36.818+0000] {standard_task_runner.py:60} INFO - Started process 2346 to run task
[2024-08-20T10:23:36.820+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_4', 'scrape_post_links', 'manual__2024-08-20T10:21:43.417140+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmpj8ftc_gt']
[2024-08-20T10:23:36.822+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask scrape_post_links
[2024-08-20T10:23:36.854+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_4.scrape_post_links manual__2024-08-20T10:21:43.417140+00:00 [running]> on host 8369baedd275
[2024-08-20T10:23:36.999+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_4' AIRFLOW_CTX_TASK_ID='scrape_post_links' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T10:21:43.417140+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T10:21:43.417140+00:00'
[2024-08-20T10:23:50.087+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-20T10:23:50.088+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 39475.80it/s]
[2024-08-20T10:23:52.529+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/11 [00:00<?, ?it/s]
[2024-08-20T10:23:52.533+0000] {logging_mixin.py:188} WARNING - 100%|##########| 11/11 [00:00<00:00, 74898.29it/s]
[2024-08-20T10:24:04.905+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-20T10:24:04.906+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 99371.47it/s]
[2024-08-20T10:24:18.742+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-20T10:24:18.748+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 82107.09it/s]
[2024-08-20T10:24:20.740+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/5 [00:00<?, ?it/s]
[2024-08-20T10:24:20.749+0000] {logging_mixin.py:188} WARNING - 100%|##########| 5/5 [00:00<00:00, 46192.78it/s]
[2024-08-20T10:24:29.293+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-20T10:24:29.294+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 35098.78it/s]
[2024-08-20T10:24:54.563+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2024-08-20T10:24:54.579+0000] {logging_mixin.py:188} WARNING - 100%|##########| 1/1 [00:00<00:00, 4401.16it/s]
[2024-08-20T10:25:05.628+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_links_extraction.py", line 68, in scrape_links
    upload_table('ikman_vehicle_post_links')
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    with open(f'/var/lib/postgresql/csv/{table_name}.csv', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/postgresql/csv/ikman_vehicle_post_links.csv'
[2024-08-20T10:25:05.742+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Data_scrape_Pipeline_4, task_id=scrape_post_links, execution_date=20240820T102143, start_date=20240820T102336, end_date=20240820T102505
[2024-08-20T10:25:05.755+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task scrape_post_links ([Errno 2] No such file or directory: '/var/lib/postgresql/csv/ikman_vehicle_post_links.csv'; 2346)
[2024-08-20T10:25:05.774+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-20T10:25:05.798+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
