[2024-08-28T06:49:06.616+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Model_Training_Pipeline.model_training_honda manual__2024-08-28T06:48:32.733443+00:00 [queued]>
[2024-08-28T06:49:06.623+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Model_Training_Pipeline.model_training_honda manual__2024-08-28T06:48:32.733443+00:00 [queued]>
[2024-08-28T06:49:06.624+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-08-28T06:49:06.649+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): model_training_honda> on 2024-08-28 06:48:32.733443+00:00
[2024-08-28T06:49:06.655+0000] {standard_task_runner.py:60} INFO - Started process 430 to run task
[2024-08-28T06:49:06.658+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Model_Training_Pipeline', 'model_training_honda', 'manual__2024-08-28T06:48:32.733443+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_model_training_pipeline.py', '--cfg-path', '/tmp/tmp6fmvhh55']
[2024-08-28T06:49:06.660+0000] {standard_task_runner.py:88} INFO - Job 288: Subtask model_training_honda
[2024-08-28T06:49:06.711+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Model_Training_Pipeline.model_training_honda manual__2024-08-28T06:48:32.733443+00:00 [running]> on host 6d604cf72944
[2024-08-28T06:49:06.794+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Model_Training_Pipeline' AIRFLOW_CTX_TASK_ID='model_training_honda' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T06:48:32.733443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T06:48:32.733443+00:00'
[2024-08-28T06:49:06.808+0000] {logging_mixin.py:188} INFO - error [Errno 2] No such file or directory: 'artifacts/preprocessor.pkl'
[2024-08-28T06:49:06.816+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/model_training_components/model_training.py", line 69, in train_model
    input_feature_train_arr=preprocessor.fit_transform(input_feature_train_df)
AttributeError: 'NoneType' object has no attribute 'fit_transform'
[2024-08-28T06:49:06.855+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Model_Training_Pipeline, task_id=model_training_honda, execution_date=20240828T064832, start_date=20240828T064906, end_date=20240828T064906
[2024-08-28T06:49:06.875+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 288 for task model_training_honda ('NoneType' object has no attribute 'fit_transform'; 430)
[2024-08-28T06:49:06.913+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-28T06:49:06.935+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
