[2024-10-10T00:00:02.447+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gold_training_Pipeline.scrape_time_series_data scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T00:00:02.452+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gold_training_Pipeline.scrape_time_series_data scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T00:00:02.453+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-10-10T00:00:02.461+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_time_series_data> on 2024-10-09 00:00:00+00:00
[2024-10-10T00:00:02.467+0000] {standard_task_runner.py:60} INFO - Started process 10341 to run task
[2024-10-10T00:00:02.469+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Gold_training_Pipeline', 'scrape_time_series_data', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/gold_training_pipeline.py', '--cfg-path', '/tmp/tmpe_y2oyru']
[2024-10-10T00:00:02.470+0000] {standard_task_runner.py:88} INFO - Job 373: Subtask scrape_time_series_data
[2024-10-10T00:00:02.503+0000] {task_command.py:423} INFO - Running <TaskInstance: Gold_training_Pipeline.scrape_time_series_data scheduled__2024-10-09T00:00:00+00:00 [running]> on host c11a805db606
[2024-10-10T00:00:02.559+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Gold_training_Pipeline' AIRFLOW_CTX_TASK_ID='scrape_time_series_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-10T00:00:02.561+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-10-10T00:00:02.566+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Gold_training_Pipeline, task_id=scrape_time_series_data, execution_date=20241009T000000, start_date=20241010T000002, end_date=20241010T000002
[2024-10-10T00:00:02.570+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-10-10T00:00:02.575+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-10-10T00:00:02.576+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-10-10T00:00:02.603+0000] {taskinstance.py:1127} ERROR - Error when executing success_email callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1124, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/components/utils/send_email.py", line 12, in success_email
    send_email(to = to_email, subject = subject, html_content = body)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[2024-10-10T00:00:02.643+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-10T00:00:02.659+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
