[2024-08-27T07:44:49.456+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Model_Training_Pipeline.data_ingestion scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-27T07:44:49.463+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Model_Training_Pipeline.data_ingestion scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-27T07:44:49.464+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-08-27T07:44:49.478+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): data_ingestion> on 2024-08-26 00:00:00+00:00
[2024-08-27T07:44:49.484+0000] {standard_task_runner.py:60} INFO - Started process 524 to run task
[2024-08-27T07:44:49.487+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Model_Training_Pipeline', 'data_ingestion', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_model_training_pipeline.py', '--cfg-path', '/tmp/tmp3f0l74ko']
[2024-08-27T07:44:49.489+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask data_ingestion
[2024-08-27T07:44:49.530+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Model_Training_Pipeline.data_ingestion scheduled__2024-08-26T00:00:00+00:00 [running]> on host 6c6a25447d9d
[2024-08-27T07:44:49.584+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Model_Training_Pipeline' AIRFLOW_CTX_TASK_ID='data_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-27T07:44:49.642+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/model_training_components/data_ingestion.py", line 38, in data_feeding
    upload_table(train_data_tabel)
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    cur.execute(f"""
psycopg2.errors.InsufficientPrivilege: could not open file "/var/lib/postgresql/gold/Micro_train_data.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2024-08-27T07:44:49.653+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Model_Training_Pipeline, task_id=data_ingestion, execution_date=20240826T000000, start_date=20240827T074449, end_date=20240827T074449
[2024-08-27T07:44:49.661+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task data_ingestion (could not open file "/var/lib/postgresql/gold/Micro_train_data.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
; 524)
[2024-08-27T07:44:49.700+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-27T07:44:49.718+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
