[2024-10-22T04:30:58.453+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Model_Training_Pipeline.data_transformation manual__2024-10-22T04:30:48.303183+00:00 [queued]>
[2024-10-22T04:30:58.458+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Model_Training_Pipeline.data_transformation manual__2024-10-22T04:30:48.303183+00:00 [queued]>
[2024-10-22T04:30:58.459+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-10-22T04:30:58.468+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): data_transformation> on 2024-10-22 04:30:48.303183+00:00
[2024-10-22T04:30:58.473+0000] {standard_task_runner.py:60} INFO - Started process 85866 to run task
[2024-10-22T04:30:58.475+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Model_Training_Pipeline', 'data_transformation', 'manual__2024-10-22T04:30:48.303183+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_model_training_pipeline.py', '--cfg-path', '/tmp/tmp76k1nt7c']
[2024-10-22T04:30:58.476+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask data_transformation
[2024-10-22T04:30:58.512+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Model_Training_Pipeline.data_transformation manual__2024-10-22T04:30:48.303183+00:00 [running]> on host 988c1a0779ad
[2024-10-22T04:30:58.560+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Model_Training_Pipeline' AIRFLOW_CTX_TASK_ID='data_transformation' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T04:30:48.303183+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T04:30:48.303183+00:00'
[2024-10-22T04:30:58.561+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-10-22T04:30:58.567+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Vehicle_Model_Training_Pipeline, task_id=data_transformation, execution_date=20241022T043048, start_date=20241022T043058, end_date=20241022T043058
[2024-10-22T04:30:58.570+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-10-22T04:30:58.575+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-10-22T04:30:58.576+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-10-22T04:31:31.130+0000] {taskinstance.py:1127} ERROR - Error when executing success_email callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1124, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/components/utils/send_email.py", line 12, in success_email
    send_email(to = to_email, subject = subject, html_content = body)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 278, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.8/smtplib.py", line 788, in starttls
    self.sock = context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1118: The handshake operation timed out
[2024-10-22T04:31:31.178+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-22T04:31:31.194+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
