[2024-08-20T10:08:56.935+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_2.scrape_vehicle_info_from_link manual__2024-08-20T10:08:49.939433+00:00 [queued]>
[2024-08-20T10:08:56.942+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_2.scrape_vehicle_info_from_link manual__2024-08-20T10:08:49.939433+00:00 [queued]>
[2024-08-20T10:08:56.957+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-08-20T10:08:56.971+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_vehicle_info_from_link> on 2024-08-20 10:08:49.939433+00:00
[2024-08-20T10:08:56.975+0000] {standard_task_runner.py:60} INFO - Started process 919 to run task
[2024-08-20T10:08:56.978+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_2', 'scrape_vehicle_info_from_link', 'manual__2024-08-20T10:08:49.939433+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmpq0k2p1zb']
[2024-08-20T10:08:56.981+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask scrape_vehicle_info_from_link
[2024-08-20T10:08:57.028+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_2.scrape_vehicle_info_from_link manual__2024-08-20T10:08:49.939433+00:00 [running]> on host 8369baedd275
[2024-08-20T10:08:57.207+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_2' AIRFLOW_CTX_TASK_ID='scrape_vehicle_info_from_link' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T10:08:49.939433+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T10:08:49.939433+00:00'
[2024-08-20T10:08:57.212+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_data_extraction.py", line 39, in scarpe_and_save
    cur.execute(query)
psycopg2.errors.UndefinedTable: relation "ikman_vehicle_post_links" does not exist
LINE 1: SELECT * FROM ikman_vehicle_post_links
                      ^

[2024-08-20T10:08:57.226+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Data_scrape_Pipeline_2, task_id=scrape_vehicle_info_from_link, execution_date=20240820T100849, start_date=20240820T100856, end_date=20240820T100857
[2024-08-20T10:08:57.239+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task scrape_vehicle_info_from_link (relation "ikman_vehicle_post_links" does not exist
LINE 1: SELECT * FROM ikman_vehicle_post_links
                      ^
; 919)
[2024-08-20T10:08:57.271+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-20T10:08:57.301+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
