[2024-10-10T10:13:18.860+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gold_training_Pipeline1.send_mails scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T10:13:18.867+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gold_training_Pipeline1.send_mails scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T10:13:18.868+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-10-10T10:13:18.878+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): send_mails> on 2024-10-09 00:00:00+00:00
[2024-10-10T10:13:18.885+0000] {standard_task_runner.py:60} INFO - Started process 15978 to run task
[2024-10-10T10:13:18.887+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Gold_training_Pipeline1', 'send_mails', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/gold_training_pipeline.py', '--cfg-path', '/tmp/tmpky08aiph']
[2024-10-10T10:13:18.888+0000] {standard_task_runner.py:88} INFO - Job 449: Subtask send_mails
[2024-10-10T10:13:18.924+0000] {task_command.py:423} INFO - Running <TaskInstance: Gold_training_Pipeline1.send_mails scheduled__2024-10-09T00:00:00+00:00 [running]> on host 3c39c54b31c0
[2024-10-10T10:13:18.986+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Gold_training_Pipeline1' AIRFLOW_CTX_TASK_ID='send_mails' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-10T10:13:18.988+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/gold/post_training/sending_mails.py", line 46, in mail_sending
    with open(attachment_path, "rb") as attachment:
FileNotFoundError: [Errno 2] No such file or directory: 'df_interpolated.csv'
[2024-10-10T10:13:19.005+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Gold_training_Pipeline1, task_id=send_mails, execution_date=20241009T000000, start_date=20241010T101318, end_date=20241010T101319
[2024-10-10T10:13:19.010+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-10-10T10:13:19.016+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-10-10T10:13:19.016+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-10-10T10:13:20.706+0000] {email.py:281} INFO - Sent an alert email to ['deshanariyarathna@gmail.com']
[2024-10-10T10:13:22.487+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 449 for task send_mails ([Errno 2] No such file or directory: 'df_interpolated.csv'; 15978)
[2024-10-10T10:13:22.514+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-10T10:13:22.526+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
